apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
       - name: httpd
         image: microservicesdep/sample
         ports: 
           - containerport: 8080
             protocol: TCP
      imagePullSecrets:
       - name: depreg
