apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
       - name: nginx
         image: microservicesdep/sample:v1
         ports: 
           - nodePort: 30303
           - containerPort: 8080
             protocol: TCP
      imagePullSecrets:
       - name: depreg
